using System.Text;
using VisualStates.Core.Models;

namespace VisualStates.Core.Generation;

public sealed class StateMachineCodeGenerator
{
    public string Generate(StateProject project)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using VisualStates.Runtime;");
        sb.AppendLine();
        sb.AppendLine($"namespace {project.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {project.GeneratedClassName} : IGeneratedStateMachine");
        sb.AppendLine("{");
        AppendVariables(sb, project);
        sb.AppendLine();
        sb.AppendLine("    public async Task RunAsync(IStateMachineContext context, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        AppendExecution(sb, project);
        sb.AppendLine("    }");
        sb.AppendLine();
        AppendStepMethods(sb, project);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendVariables(StringBuilder sb, StateProject project)
    {
        foreach (var variable in project.Variables)
        {
            if (!string.IsNullOrWhiteSpace(variable.DefaultValue))
                sb.AppendLine($"    public {variable.TypeName} {SanitizeIdentifier(variable.Name)} {{ get; set; }} = {variable.DefaultValue};");
            else
                sb.AppendLine($"    public {variable.TypeName} {SanitizeIdentifier(variable.Name)} {{ get; set; }}");
        }
    }

    private static void AppendExecution(StringBuilder sb, StateProject project)
    {
        var order = ExecutionOrderBuilder.Build(project);
        if (order.Count == 0)
        {
            sb.AppendLine("        await Task.CompletedTask;");
            return;
        }

        foreach (var node in order)
        {
            sb.AppendLine($"        await {MethodName(node)}(context, cancellationToken);");
        }
    }

    private static void AppendStepMethods(StringBuilder sb, StateProject project)
    {
        foreach (var box in project.Boxes)
        {
            foreach (var step in box.Steps)
            {
                var node = new ExecutionNode(box.Id, step.Id);
                AppendStepMethod(sb, project, box, step, node);
            }

            if (box.Steps.Count == 0)
            {
                var node = new ExecutionNode(box.Id, null);
                AppendEmptyBoxMethod(sb, box, node);
            }
        }
    }

    private static void AppendStepMethod(StringBuilder sb, StateProject project, StateBox box, StateStep step, ExecutionNode node)
    {
        sb.AppendLine($"    private async Task {MethodName(node)}(IStateMachineContext context, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine($"        // {box.Name} / {step.Name}");
        switch (step.Kind)
        {
            case StepKind.SetVariable:
                var variable = step.TargetName ?? "Variable";
                var expression = step.Expression ?? "null";
                sb.AppendLine($"        {SanitizeIdentifier(variable)} = {expression};");
                sb.AppendLine("        await Task.CompletedTask;");
                break;
            case StepKind.CallEvent:
                var eventName = step.EventName ?? step.TargetName ?? "OnEvent";
                sb.AppendLine($"        await context.RaiseEventAsync(\"{eventName}\", cancellationToken);");
                break;
            case StepKind.CallMethod:
                var method = step.MethodName ?? step.TargetName ?? "Execute";
                var args = string.IsNullOrWhiteSpace(step.Arguments) ? string.Empty : $", {step.Arguments}";
                sb.AppendLine($"        await context.InvokeMethodAsync(\"{method}\"{args}, cancellationToken);");
                break;
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendEmptyBoxMethod(StringBuilder sb, StateBox box, ExecutionNode node)
    {
        sb.AppendLine($"    private async Task {MethodName(node)}(IStateMachineContext context, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine($"        // {box.Name}");
        sb.AppendLine("        await Task.CompletedTask;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string MethodName(ExecutionNode node) =>
        $"Step_{node.BoxId.Replace("-", string.Empty)[..8]}_{node.StepId?.Replace("-", string.Empty)[..8] ?? "entry"}";

    private static string SanitizeIdentifier(string value)
    {
        var cleaned = new string(value.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
        if (string.IsNullOrWhiteSpace(cleaned) || char.IsDigit(cleaned[0]))
            return "_" + cleaned;
        return cleaned;
    }
}

internal readonly record struct ExecutionNode(string BoxId, string? StepId);

internal static class ExecutionOrderBuilder
{
    public static IReadOnlyList<ExecutionNode> Build(StateProject project)
    {
        var nodes = new List<ExecutionNode>();
        foreach (var box in project.Boxes)
        {
            if (box.Steps.Count == 0)
                nodes.Add(new ExecutionNode(box.Id, null));
            else
                nodes.AddRange(box.Steps.Select(step => new ExecutionNode(box.Id, step.Id)));
        }

        if (nodes.Count == 0)
            return nodes;

        var nodeSet = nodes.ToHashSet();
        var incoming = nodes.ToDictionary(n => n, _ => 0);
        var adjacency = nodes.ToDictionary(n => n, _ => new List<ExecutionNode>());

        foreach (var connection in project.Connections)
        {
            var source = ToNode(project, connection.SourceBoxId, connection.SourceStepId);
            var target = ToNode(project, connection.TargetBoxId, connection.TargetStepId);
            if (!nodeSet.Contains(source) || !nodeSet.Contains(target) || source.Equals(target))
                continue;

            adjacency[source].Add(target);
            incoming[target]++;
        }

        var queue = new Queue<ExecutionNode>(
            incoming.Where(kv => kv.Value == 0).Select(kv => kv.Key));

        if (queue.Count == 0)
        {
            var entryBox = project.Boxes.FirstOrDefault(b => b.IsEntry) ?? project.Boxes.FirstOrDefault();
            if (entryBox is not null)
            {
                var entryNode = entryBox.Steps.Count > 0
                    ? new ExecutionNode(entryBox.Id, entryBox.Steps[0].Id)
                    : new ExecutionNode(entryBox.Id, null);
                queue.Enqueue(entryNode);
            }
            else
            {
                queue.Enqueue(nodes[0]);
            }
        }

        var ordered = new List<ExecutionNode>();
        var visited = new HashSet<ExecutionNode>();
        while (queue.Count > 0)
        {
            var current = queue.Dequeue();
            if (!visited.Add(current))
                continue;

            ordered.Add(current);
            foreach (var next in adjacency[current])
            {
                incoming[next]--;
                if (incoming[next] == 0)
                    queue.Enqueue(next);
            }
        }

        foreach (var node in nodes)
        {
            if (!visited.Contains(node))
                ordered.Add(node);
        }

        return ordered;
    }

    private static ExecutionNode ToNode(StateProject project, string boxId, string? stepId)
    {
        var box = project.FindBox(boxId);
        if (box is null)
            return new ExecutionNode(boxId, stepId);

        if (!string.IsNullOrWhiteSpace(stepId) && box.Steps.Any(s => s.Id == stepId))
            return new ExecutionNode(box.Id, stepId);

        if (box.Steps.Count > 0)
            return new ExecutionNode(box.Id, box.Steps[^1].Id);

        return new ExecutionNode(box.Id, null);
    }
}
