using System.Text;
using VisualStates.Core;
using VisualStates.Core.Models;

namespace VisualStates.Core.Generation;

public sealed class StateMachineCodeGenerator
{
    public string Generate(StateProject project)
    {
        var methodNames = BuildMethodNames(project);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using VisualStates.Runtime;");
        sb.AppendLine();
        sb.AppendLine($"namespace {project.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {project.GeneratedClassName} : IGeneratedStateMachine");
        sb.AppendLine("{");
        AppendVariables(sb, project);
        sb.AppendLine();
        sb.AppendLine("    public async Task RunAsync(IStateMachineContext context, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        AppendExecution(sb, project, methodNames);
        sb.AppendLine("    }");
        sb.AppendLine();
        AppendStepMethods(sb, project, methodNames);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendVariables(StringBuilder sb, StateProject project)
    {
        foreach (var variable in project.Variables)
        {
            if (!string.IsNullOrWhiteSpace(variable.DefaultValue))
                sb.AppendLine($"    public {variable.TypeName} {SanitizeIdentifier(variable.Name)} {{ get; set; }} = {variable.DefaultValue};");
            else
                sb.AppendLine($"    public {variable.TypeName} {SanitizeIdentifier(variable.Name)} {{ get; set; }}");
        }
    }

    private static void AppendExecution(
        StringBuilder sb, StateProject project, IReadOnlyDictionary<ExecutionNode, string> methodNames)
    {
        var order = ExecutionOrderBuilder.Build(project);
        if (order.Count == 0)
        {
            sb.AppendLine("        await Task.CompletedTask;");
            return;
        }

        foreach (var node in order)
        {
            sb.AppendLine($"        await {methodNames[node]}(context, cancellationToken);");
        }
    }

    private static void AppendStepMethods(
        StringBuilder sb, StateProject project, IReadOnlyDictionary<ExecutionNode, string> methodNames)
    {
        foreach (var box in project.Boxes)
        {
            foreach (var step in box.Steps)
            {
                var node = new ExecutionNode(box.Id, step.Id);
                AppendStepMethod(sb, project, box, step, methodNames[node]);
            }

            if (box.Steps.Count == 0)
            {
                var node = new ExecutionNode(box.Id, null);
                AppendEmptyBoxMethod(sb, box, methodNames[node]);
            }
        }
    }

    private static void AppendStepMethod(
        StringBuilder sb, StateProject project, StateBox box, StateStep step, string methodName)
    {
        sb.AppendLine($"    private async Task {methodName}(IStateMachineContext context, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine($"        // {box.Name} / {step.Name}");
        switch (step.Kind)
        {
            case StepKind.SetVariable:
                var variable = step.TargetName ?? "Variable";
                var expression = step.Expression ?? "null";
                sb.AppendLine($"        {SanitizeIdentifier(variable)} = {expression};");
                sb.AppendLine("        await Task.CompletedTask;");
                break;
            case StepKind.CallEvent:
                var eventName = step.EventName ?? step.TargetName ?? "OnEvent";
                sb.AppendLine($"        await context.RaiseEventAsync(\"{eventName}\", cancellationToken);");
                break;
            case StepKind.CallMethod:
                var method = step.MethodName ?? step.TargetName ?? "Execute";
                var args = string.IsNullOrWhiteSpace(step.Arguments) ? string.Empty : $", {step.Arguments}";
                sb.AppendLine($"        await context.InvokeMethodAsync(\"{method}\"{args}, cancellationToken);");
                break;
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendEmptyBoxMethod(StringBuilder sb, StateBox box, string methodName)
    {
        sb.AppendLine($"    private async Task {methodName}(IStateMachineContext context, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine($"        // {box.Name}");
        sb.AppendLine("        await Task.CompletedTask;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static Dictionary<ExecutionNode, string> BuildMethodNames(StateProject project)
    {
        var used = new HashSet<string>(StringComparer.Ordinal);
        var map = new Dictionary<ExecutionNode, string>();

        foreach (var box in project.Boxes)
        {
            if (box.Steps.Count == 0)
            {
                var node = new ExecutionNode(box.Id, null);
                map[node] = AllocateUniqueName(SuggestEmptyBoxName(box), used);
                continue;
            }

            foreach (var step in box.Steps)
            {
                var node = new ExecutionNode(box.Id, step.Id);
                map[node] = AllocateUniqueName(SuggestStepName(box, step), used);
            }
        }

        return map;
    }

    private static string SuggestEmptyBoxName(StateBox box) =>
        ToPascalIdentifier(box.Name) is { Length: > 0 } name ? name : "State";

    private static string SuggestStepName(StateBox box, StateStep step)
    {
        var boxPart = ToPascalIdentifier(box.Name);
        if (string.IsNullOrEmpty(boxPart))
            boxPart = "State";

        var action = step.Kind switch
        {
            StepKind.SetVariable => "Set" + ToPascalIdentifier(step.TargetName ?? step.Name ?? "Variable"),
            StepKind.CallEvent => ToPascalIdentifier(step.EventName ?? step.TargetName ?? step.Name ?? "OnEvent"),
            StepKind.CallMethod => ToPascalIdentifier(step.MethodName ?? step.TargetName ?? step.Name ?? "Execute"),
            _ => ToPascalIdentifier(step.Name)
        };

        if (string.IsNullOrEmpty(action))
            action = "Step";

        return $"{boxPart}_{action}";
    }

    private static string AllocateUniqueName(string preferred, HashSet<string> used)
    {
        var name = preferred;
        var suffix = 2;
        while (!used.Add(name))
        {
            name = $"{preferred}_{suffix}";
            suffix++;
        }

        return name;
    }

    /// <summary>
    /// Turns display text like "State 2" / "On Enter" into a PascalCase identifier.
    /// </summary>
    private static string ToPascalIdentifier(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return string.Empty;

        var parts = new List<string>();
        var current = new StringBuilder();
        foreach (var ch in value.Trim())
        {
            if (char.IsLetterOrDigit(ch))
            {
                current.Append(ch);
                continue;
            }

            if (current.Length > 0)
            {
                parts.Add(current.ToString());
                current.Clear();
            }
        }

        if (current.Length > 0)
            parts.Add(current.ToString());

        if (parts.Count == 0)
            return string.Empty;

        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0)
                continue;
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                sb.Append(part[1..]);
        }

        return SanitizeIdentifier(sb.ToString());
    }

    private static string SanitizeIdentifier(string value)
    {
        var cleaned = new string(value.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
        if (string.IsNullOrWhiteSpace(cleaned))
            return "_Step";
        if (char.IsDigit(cleaned[0]))
            return "_" + cleaned;
        return cleaned;
    }
}

internal readonly record struct ExecutionNode(string BoxId, string? StepId);

internal static class ExecutionOrderBuilder
{
    public static IReadOnlyList<ExecutionNode> Build(StateProject project)
    {
        var nodes = new List<ExecutionNode>();
        foreach (var box in project.Boxes)
        {
            if (box.Steps.Count == 0)
                nodes.Add(new ExecutionNode(box.Id, null));
            else
                nodes.AddRange(box.Steps.Select(step => new ExecutionNode(box.Id, step.Id)));
        }

        if (nodes.Count == 0)
            return nodes;

        var nodeSet = nodes.ToHashSet();
        var incoming = nodes.ToDictionary(n => n, _ => 0);
        var adjacency = nodes.ToDictionary(n => n, _ => new List<ExecutionNode>());

        void AddEdge(ExecutionNode source, ExecutionNode target)
        {
            if (!nodeSet.Contains(source) || !nodeSet.Contains(target) || source.Equals(target))
                return;

            adjacency[source].Add(target);
            incoming[target]++;
        }

        foreach (var connection in project.Connections)
        {
            var source = ResolveConnectionSource(project, connection);
            var target = ResolveConnectionTarget(project, connection);
            if (source is null || target is null)
                continue;

            AddEdge(source.Value, target.Value);
        }

        // Within each zone, chain children in visual order so generated sequence
        // follows enter → first → … → last → exit.
        foreach (var zone in project.Zones)
        {
            var children = ZoneFlow.GetOrderedChildren(project, zone.Id);
            foreach (var child in children)
            {
                for (var s = 0; s < child.Steps.Count - 1; s++)
                {
                    AddEdge(
                        new ExecutionNode(child.Id, child.Steps[s].Id),
                        new ExecutionNode(child.Id, child.Steps[s + 1].Id));
                }
            }

            for (var i = 0; i < children.Count - 1; i++)
            {
                var from = BoxExitNode(children[i]);
                var to = BoxEnterNode(children[i + 1]);
                AddEdge(from, to);
            }
        }

        var queue = new Queue<ExecutionNode>(
            incoming.Where(kv => kv.Value == 0).Select(kv => kv.Key));

        if (queue.Count == 0)
        {
            var entryBox = project.Boxes.FirstOrDefault(b => b.IsEntry) ?? project.Boxes.FirstOrDefault();
            if (entryBox is not null)
            {
                var entryNode = entryBox.Steps.Count > 0
                    ? new ExecutionNode(entryBox.Id, entryBox.Steps[0].Id)
                    : new ExecutionNode(entryBox.Id, null);
                queue.Enqueue(entryNode);
            }
            else
            {
                queue.Enqueue(nodes[0]);
            }
        }

        var ordered = new List<ExecutionNode>();
        var visited = new HashSet<ExecutionNode>();
        while (queue.Count > 0)
        {
            var current = queue.Dequeue();
            if (!visited.Add(current))
                continue;

            ordered.Add(current);
            foreach (var next in adjacency[current])
            {
                incoming[next]--;
                if (incoming[next] == 0)
                    queue.Enqueue(next);
            }
        }

        foreach (var node in nodes)
        {
            if (!visited.Contains(node))
                ordered.Add(node);
        }

        return ordered;
    }

    private static ExecutionNode? ResolveConnectionSource(StateProject project, StateConnection connection)
    {
        if (!string.IsNullOrWhiteSpace(connection.SourceZoneId))
        {
            var exit = ZoneFlow.ResolveExit(project, connection.SourceZoneId);
            return exit is null ? null : new ExecutionNode(exit.Value.BoxId, exit.Value.StepId);
        }

        return ToNode(project, connection.SourceBoxId, connection.SourceStepId);
    }

    private static ExecutionNode? ResolveConnectionTarget(StateProject project, StateConnection connection)
    {
        if (!string.IsNullOrWhiteSpace(connection.TargetZoneId))
        {
            var enter = ZoneFlow.ResolveEnter(project, connection.TargetZoneId);
            return enter is null ? null : new ExecutionNode(enter.Value.BoxId, enter.Value.StepId);
        }

        return ToNode(project, connection.TargetBoxId, connection.TargetStepId);
    }

    private static ExecutionNode BoxEnterNode(StateBox box) =>
        box.Steps.Count > 0
            ? new ExecutionNode(box.Id, box.Steps[0].Id)
            : new ExecutionNode(box.Id, null);

    private static ExecutionNode BoxExitNode(StateBox box) =>
        box.Steps.Count > 0
            ? new ExecutionNode(box.Id, box.Steps[^1].Id)
            : new ExecutionNode(box.Id, null);

    private static ExecutionNode ToNode(StateProject project, string boxId, string? stepId)
    {
        var box = project.FindBox(boxId);
        if (box is null)
            return new ExecutionNode(boxId, stepId);

        if (!string.IsNullOrWhiteSpace(stepId) && box.Steps.Any(s => s.Id == stepId))
            return new ExecutionNode(box.Id, stepId);

        if (box.Steps.Count > 0)
            return new ExecutionNode(box.Id, box.Steps[^1].Id);

        return new ExecutionNode(box.Id, null);
    }
}
