<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.0</Version>
    <Authors>aruantec</Authors>
    <Company>aruantec</Company>
    <Product>VisualStates</Product>
    <Copyright>Copyright (c) 2026 Joel Fung</Copyright>
  </PropertyGroup>
</Project>
